// <auto-generated />
using System;
using FarmaciaAvellaneda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmaciaAvellaneda.Migrations.FarmaciaAvellaneda
{
    [DbContext(typeof(FarmaciaAvellanedaContext))]
    [Migration("20201121082245_FarmaciaMigration")]
    partial class FarmaciaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetRoleClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserLogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<double?>("Saldo")
                        .HasColumnName("saldo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Caja");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Capacidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("int");

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductoId")
                        .HasColumnName("productoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Capacidad");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("CategoriaProducto");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<double?>("Total")
                        .HasColumnName("total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Concepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<double?>("MontoFijo")
                        .HasColumnName("montoFijo")
                        .HasColumnType("float");

                    b.Property<double?>("MontoVariable")
                        .HasColumnName("montoVariable")
                        .HasColumnType("float");

                    b.Property<byte?>("Tipo")
                        .HasColumnName("tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Concepto");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.DetalleLiquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConceptoId")
                        .HasColumnName("conceptoId")
                        .HasColumnType("int");

                    b.Property<string>("Haberes")
                        .HasColumnName("haberes")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<int>("LiquidacionId")
                        .HasColumnName("liquidacionId")
                        .HasColumnType("int");

                    b.Property<int?>("Unidad")
                        .HasColumnName("unidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoId");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("DetalleLiquidacion");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("apellido")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Celular")
                        .HasColumnName("celular")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Cuit")
                        .HasColumnName("cuit")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Domicilio")
                        .HasColumnName("domicilio")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasName("UQ__Empleado__CB9A1CFE35DEA35C");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.GrupoFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnName("apellido")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("Dni")
                        .HasColumnName("dni")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnName("empleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnName("fechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Parentesco")
                        .HasColumnName("parentesco")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("GrupoFamiliar");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.LineaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnName("compraId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnName("productoId")
                        .HasColumnType("int");

                    b.Property<double?>("Subtotal")
                        .HasColumnName("subtotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LineaCompra");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.LineaVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnName("productoId")
                        .HasColumnType("int");

                    b.Property<double?>("Subtotal")
                        .HasColumnName("subtotal")
                        .HasColumnType("float");

                    b.Property<int>("VentaId")
                        .HasColumnName("ventaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("LineaVenta");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoId")
                        .HasColumnName("empleadoId")
                        .HasColumnType("int");

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnName("fechaDesde")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnName("fechaHasta")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PeriodoLiquidacion")
                        .HasColumnName("periodoLiquidacion")
                        .HasColumnType("date");

                    b.Property<double?>("Retenciones")
                        .HasColumnName("retenciones")
                        .HasColumnType("float");

                    b.Property<double?>("SalarioBruto")
                        .HasColumnName("salarioBruto")
                        .HasColumnType("float");

                    b.Property<double?>("SalarioNeto")
                        .HasColumnName("salarioNeto")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Liquidacion");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Codigo")
                        .HasColumnName("codigo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(45)")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CajaId")
                        .HasColumnName("cajaId")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnName("compraId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("VentaId")
                        .HasColumnName("ventaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("CompraId");

                    b.HasIndex("VentaId");

                    b.ToTable("MovimientoCaja");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Monto")
                        .HasColumnName("monto")
                        .HasColumnType("float");

                    b.Property<int>("VentaId")
                        .HasColumnName("ventaId")
                        .HasColumnType("int");

                    b.Property<double?>("Vuelto")
                        .HasColumnName("vuelto")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("VentaId")
                        .IsUnique()
                        .HasName("UQ__Pago__40B8EB55CE174DFA");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaProductoId")
                        .HasColumnName("categoriaProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnName("fechaVencimiento")
                        .HasColumnType("date");

                    b.Property<byte[]>("Foto")
                        .HasColumnName("foto")
                        .HasColumnType("image");

                    b.Property<int>("MarcaId")
                        .HasColumnName("marcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<double?>("PrecioCompra")
                        .HasColumnName("precioCompra")
                        .HasColumnType("float");

                    b.Property<double?>("PrecioVenta")
                        .HasColumnName("precioVenta")
                        .HasColumnType("float");

                    b.Property<int>("ProveedorId")
                        .HasColumnName("proveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .HasColumnName("stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProductoId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompraId")
                        .HasColumnName("compraId")
                        .HasColumnType("int");

                    b.Property<string>("Cuit")
                        .HasColumnName("cuit")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("RazonSocial")
                        .HasColumnName("razonSocial")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.SubCategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaProductoId")
                        .HasColumnName("categoriaProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProductoId");

                    b.ToTable("SubCategoriaProducto");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoId")
                        .HasColumnName("empleadoId")
                        .HasColumnType("int");

                    b.Property<byte?>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnName("fechaVenta")
                        .HasColumnType("datetime");

                    b.Property<double?>("Total")
                        .HasColumnName("total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetRoleClaims", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.AspNetRoles", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserClaims", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserLogins", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserRoles", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.AspNetRoles", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.AspNetUserTokens", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Capacidad", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Producto", "Producto")
                        .WithMany("Capacidad")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK_Capacidad_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.DetalleLiquidacion", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Concepto", "Concepto")
                        .WithMany("DetalleLiquidacion")
                        .HasForeignKey("ConceptoId")
                        .HasConstraintName("FK_DetalleLiquidacion_Concepto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Liquidacion", "Liquidacion")
                        .WithMany("DetalleLiquidacion")
                        .HasForeignKey("LiquidacionId")
                        .HasConstraintName("FK_DetalleLiquidacion_Liquidacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Empleado", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.AspNetUsers", "User")
                        .WithOne("Empleado")
                        .HasForeignKey("FarmaciaAvellaneda.Models.Empleado", "UserId")
                        .HasConstraintName("FK_Empleado_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.GrupoFamiliar", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Empleado", "Empleado")
                        .WithMany("GrupoFamiliar")
                        .HasForeignKey("EmpleadoId")
                        .HasConstraintName("FK_GrupoFamiliar_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.LineaCompra", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Compra", "Compra")
                        .WithMany("LineaCompra")
                        .HasForeignKey("CompraId")
                        .HasConstraintName("FK_LineaCompra_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Producto", "Producto")
                        .WithMany("LineaCompra")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK_LineaCompra_Producto")
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.LineaVenta", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Producto", "Producto")
                        .WithMany("LineaVenta")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK_LineaVenta_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Venta", "Venta")
                        .WithMany("LineaVenta")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK_LineaVenta_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Liquidacion", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Empleado", "Empleado")
                        .WithMany("Liquidacion")
                        .HasForeignKey("EmpleadoId")
                        .HasConstraintName("FK_Liquidacion_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.MovimientoCaja", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Caja", "Caja")
                        .WithMany("MovimientoCaja")
                        .HasForeignKey("CajaId")
                        .HasConstraintName("FK_MovimientoCaja_Caja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Compra", "Compra")
                        .WithMany("MovimientoCaja")
                        .HasForeignKey("CompraId")
                        .HasConstraintName("FK_MovimientoCaja_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Venta", "Venta")
                        .WithMany("MovimientoCaja")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK_MovimientoCaja_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Pago", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Venta", "Venta")
                        .WithOne("Pago")
                        .HasForeignKey("FarmaciaAvellaneda.Models.Pago", "VentaId")
                        .HasConstraintName("FK_Pago_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Producto", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Producto")
                        .HasForeignKey("CategoriaProductoId")
                        .HasConstraintName("FK_Producto_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Marca", "Marca")
                        .WithMany("Producto")
                        .HasForeignKey("MarcaId")
                        .HasConstraintName("FK_Producto_Marca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmaciaAvellaneda.Models.Proveedor", "Proveedor")
                        .WithMany("Producto")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("FK_Producto_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Proveedor", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Compra", "Compra")
                        .WithMany("Proveedor")
                        .HasForeignKey("CompraId")
                        .HasConstraintName("FK_Proveedor_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.SubCategoriaProducto", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.CategoriaProducto", "CategoriaProducto")
                        .WithMany("SubCategoriaProducto")
                        .HasForeignKey("CategoriaProductoId")
                        .HasConstraintName("FK_SubCategoria_Categoria_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmaciaAvellaneda.Models.Venta", b =>
                {
                    b.HasOne("FarmaciaAvellaneda.Models.Empleado", "Empleado")
                        .WithMany("Venta")
                        .HasForeignKey("EmpleadoId")
                        .HasConstraintName("FK_Venta_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
